### ISSUE TITLE
Знакомство с TypeScript

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/oksssvv.github.io#3]
### Задача
Ознакомиться с азами работы с языками программирования на примере TypeScript, научиться покрывать простые кейсы по автоматизации задач с помощью ЯП и выполнить задание

План
 - [x] Переменные и типы данных
 - [x] Структуры данных
 - [x] Условия
 - [x] Циклы
 - [x] Функции
 - [x] Работа с ошибками
 - [x] База Advanced JS API (методы массивов)
### Задание
Необходимо реализовать простой механизм авторизации. Должны быть удовлетворены следующие требования:

 - [x] Должны присутствовать функции для регистрации:
- `login(username, password)` - вход
- `logout()` - выход
- `register(username, password)` - регистрация
- `whoami()` - получение авторизованного на данный момент пользователя (сессии)
 - [x] При регистрации должна быть проверка: логин должен быть не короче 5 символов, пароль должен быть не короче 6. Если условие не выполняется - выбрасывать ошибку
 - [x] Должна быть возможность хранить креды (`credentials`) для нескольких пользователей
 - [x] При попытке сделать логаут без активной сессии - должна выбрасываться ошибка
 - [x] При попытке сделать `whoami` без активной сессии - выбрасывать ошибку
 - [x] При удачном вызове `whoami` в консоли должен быть вывод логина пользователя, который авторизован в данный момент
 - [x] При попытке сделать регистрацию/логин в момент, когда уже есть активная сессия - выбрасывать ошибку
 - [x] Все данные должны быть типизированы: аргументы функций, используемые переменные, возвращаемые функциями значения
#### Требования к обработке ошибок:

Ошибки (и код в целом) не должны содержать символов кириллицы, при этом в некоторых ошибках должны использоваться [шаблонные строки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals). Пример:

`User with login Dassfgfd not found`

`Password for user Johnathan is incorrect`

### Требования к оформлению задания
Задание должно быть выполнено в отдельной ветке. К этой ветке должен быть создан pull request. Если pull request еще не готов к мержу в мастер - он должен быть помечен как draft. Код должен удовлетворять проверкам lint и typecheck (`yarn lint`, `yarn typecheck`)

**Comment by oksssvv** [comment]
1.  в каком виде это осуществлять? чисто на функциях или целый класс создавать, я впервые такое делаю, так что пока не вдуплила до конца (после простейших уроков на ютубе))
2. не совсем поняла про креды, каким образом осуществить их хранение, д и всё после регистрации пользователя - для меня впервые

**Comment by oxiqod** [comment]
@eshevlyakova 

**Скоуп**
Механизм авторизации пользователя

**Вопросы**
1. Должна быть связка TypeScript'a и html страницы?
2. Каким образом должен осуществляться logout() если у меня нет серверной части? Если она не нужна, то можно уточнения к этому пункту

**Личный комментарий**
Мне удалось создать простую функцию с регистрацией пользователя, поставить в ней условия для создания имени и пароля, но я не представляю как воплотить в жизнь последующие задачи в рамках своих знаний.

**Comment by eshevlyakova** [comment]
@oksssvv 
> Должна быть связка TypeScript'a и html страницы?

Нет

> Каким образом должен осуществляться logout() если у меня нет серверной части? Если она не нужна, то можно уточнения к этому пункту

Данные пользователей должны храниться просто в оперативной памяти

**Comment by oxiqod** [comment]
@eshevlyakova

**Вопросы**
Где создавать pull reques? Имею ввиду в этом шаблоне или у на моем личном профиле в гитхабе?

**Comment by eshevlyakova** [comment]
@oksssvv 

> Где создавать pull reques? Имею ввиду в этом шаблоне или у на моем личном профиле в гитхабе?

Пулл реквесты нужно создавать в этом репозитории

**Comment by oxiqod** [comment]
@eshevlyakova

**Вопрос**
1. У меня во всех функциях возврат на console.log(), или лучше сделать return?

**Comment by TorinAsakura** [comment]
@oksssvv console.log предназначен для отладки, а не для возврата результата

**Comment by TorinAsakura** [comment]
@oksssvv Если ты читала гайд по тайпскрипт то там есть рекомендации по написанию кода. Судя по вопросам - чтение если и было то крайне беглое.

**Comment by oxiqod** [comment]
@TorinAsakura 
return'ы не выводит для наглядности, поэтому везде возврат типа : void, поняла, сейчас заменю.
