### ISSUE TITLE
Знакомство с GraphQL

### ISSUE THREAD

**Issue by oxiqod** [atls-academy/oksssvv.github.io#33]
## Цель

Ознакомиться с **GraphQL**, инструментом коммуникации между front-end и back-end.

### План
- [x] Коммуникация с сервером - как и с помощью чего [(MDN 1)](https://developer.mozilla.org/ru/docs/Learn/Server-side/First_steps/Introduction) [(MDN 2)](https://developer.mozilla.org/ru/docs/Learn/Server-side/First_steps/Client-Server_overview) [(github RU, до "Веб-сервер")](https://amiskov.github.io/frontend-handbook/web/#что-происходит-при-http-запросе)
- Факультативно: покидать REST API запросы к [Star Wars API](https://swapi.dev) с помощью [`curl`](https://www.baeldung.com/curl-rest)
- [x] [**REST**](https://habr.com/ru/articles/483202/) и [**GraphQL**](https://graphql.org/learn/): сходства и различия [(aws.amazon.com RU)](https://aws.amazon.com/ru/compare/the-difference-between-graphql-and-rest/) [(habr RU)](https://habr.com/ru/companies/rshb/articles/593115/)
- [x] Виды запросов/операций (`query`, `mutation`, `subscription`) [(ресурс RU)](https://senior.ua/articles/rest-api-vs-graphql-chto-vybrat-dlya-konkretnogo-proekta) [(hexlet RU)](https://ru.hexlet.io/blog/posts/chto-takoe-graphql-s-osnov-do-pervyh-zaprosov#kak-rabotat-s-serverom-graphql)
- [x] Схема **GraphQL**: формирование запросов ([оф. документация EN](https://graphql.org/learn/schema/))
- [x] [`Apollo Client`](https://www.apollographql.com/docs/): наш инструмент коммуникации с сервером. [(habr RU)](https://habr.com/ru/articles/358292/), [(видео EN)](https://www.youtube.com/watch?v=YyUWW04HwKY)

**Comment by Nelfimov** [comment]
# Первое задание

Наш эндпоинт: https://wp.api.atls.academy/graphql

Необходимо по нему получить следующие сущности:
- [ ] Navigation
- [ ] Section
  - [ ] Hero

## Пример

**Hero** должен тебе вернуть:
```
Digital становится всё более многолюдным, востребованность...
```

## Материалы

- Для GraphQL мы используем `@apollo/client`, с которым ты выше познакомилась.
- **drum-in** - оформление кода и реализация.

**Comment by oxiqod** [comment]
@Nelfimov 

**Вопрос**
каким образом я могу получить структуру `схемы`? для понимания как именно составлять запросы к серверу

**Comment by Nelfimov** [comment]
Вот пример схемы до `sections`:

```GraphQL
query NewQuery {
  sections {
    nodes {
      content
    }
  }
}
```

**Comment by oxiqod** [comment]
@Nelfimov 

У меня удалось получить данные в виде строки для фрагмента `Info` (у меня там находится этот эта текстовая часть), добавила данные в компонент, вот как это выглядит на мобильной версии:

![Снимок экрана от 2023-08-08 09-38-40](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/b17b5b17-29c5-44c5-8fca-525157894c6c)


**Воспроизведение**
1. добавила слой `globals/data`
2. завернула в `ApolloProvider` всё, что идет в рендер
3. добавила в нужный фрагмент запрос к `gql` и хук `useInfo`
4. добавила в компонент полученную строку 

**Описание**
с сервера приходит такая сплошная строка с текстом и переносами: 
`"\nDigital становится всё более многолюдным, востребованность по направлениям при этом не снижается. Но специалистов, готовых нести ответственность за свои решения по-прежнему мало.\nAtlantis Academy обучает и формирует инженеров и архитекторов, а не программистов и дизайнеров.\n"`

по макету на десктопной версии между строками есть элементы:
![Снимок экрана от 2023-08-08 09-35-39](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/02b038fd-92a0-428c-9a2a-20ed404ce0ad)

а на мобильной версии между двумя параграфами есть отступ:
![Снимок экрана от 2023-08-08 09-37-39](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/77fa972f-83ac-4dbe-b8b7-80354ab2151c)

**Вопрос**
Так задумано? или мне нужно каким то образом форматировать полученную с сервера строку и делать отступ для мобильной версии и делить строку на 3 фрагмента для десктопной?

**Comment by Nelfimov** [comment]
Так задумано - надо делать форматирование на стороне клиента.

В десктопе - замена "." на картинки. В обоих - разделить по "\n" на несколько тегов.

**Comment by Nelfimov** [comment]
# Продолжение первого задания

Добавил тебе новые записи в `sections`:
- `title`: заголовок в секции, например в FAQ: "Вопросы и ответы"
- `navigationName`: название секции для навбара и скроллспая
- `content`: текст под заголовком

<details>
<summary>схема</summary>

```graphql
sections {
  nodes {
    content
    title
    sections {
      title
      navigationName
    }
  }
}
```

</details>

Так же можешь подтянуть уже ссылки для навбара:

<details>

```graphql
allNavigation {
  nodes {
    navigation {
      linkName
    }
    title
  }
}
```

</details>

**Comment by Nelfimov** [comment]
# Секция FAQ

Контент для секции FAQ готов.

<details>

```graphql
allFAQ {
  nodes {
    faq {
      answer
      question
    }
  }
}
```

</details>

**Comment by Nelfimov** [comment]
# Секция Скиллы (бегущая строка)

Контент для секции готов.

<details>

```graphql
skills {
  nodes {
    title
  }
}
```

</details>

**Comment by Nelfimov** [comment]
# Секция Курсы

<details>

```graphql
courses {
    nodes {
      course {
        title
        description
        label {
          ... on Label {
          id
          title
        }
      }
    }
  }
}
```

</details>

**Comment by oxiqod** [comment]
@Nelfimov 
https://github.com/atls-academy/oksssvv.github.io/issues/33#issuecomment-1669214372

по макету там title с большой буквы, а responce получаю с маленькой, или не критично?

или же мне самой просто сделать первую букву апперкейс?

**Comment by Nelfimov** [comment]
Делаем как по дизайну - у клиента трансформируем в заглавные.

**Comment by oxiqod** [comment]
@Nelfimov 

накопилось несколько уточнений по данным с сервера

Курсы:
- Дескрипций для карточек еще нет?
- Во вторую, большую карточку с заголовком `Основы разработки` приходит название лейбла `обучение`, по макету там `мини-курс`

Навбар в левой части сайта:
- с сервера приходит 4 заголовка (Academy,Курсы,Обучение,FAQ), в макете 6 (Academy,Курсы,Ученики,Обучение,Стипендия,FAQ)

Бегущая строка:
- Правильно ли я поняла, что пока готова только первая строка со скиллами, а `github atom figma` еще нет?

**Comment by Nelfimov** [comment]
> Дескрипций для карточек еще нет?

Все есть:

<details>

![image](https://github.com/atls-academy/oksssvv.github.io/assets/44067768/b5afd884-6a4c-426a-9c90-e0557d743aec)

</details>

> Во вторую, большую карточку с заголовком Основы разработки приходит название лейбла обучение, по макету там мини-курс

Обновил.

> с сервера приходит 4 заголовка (Academy,Курсы,Обучение,FAQ), в макете 6 (Academy,Курсы,Ученики,Обучение,Стипендия,FAQ)

Это косяк макета - у тебя скроллспай должен соответствовать верхнему навбару.

> Правильно ли я поняла, что пока готова только первая строка со скиллами, а github atom figma еще нет?

Добавил

**Comment by oxiqod** [comment]
@Nelfimov 
![Снимок экрана от 2023-08-10 10-49-00](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/5d4434d7-33c4-4639-8257-5626a77f23f5)

наоборот) во вторую карточку мини-курс с заголовком `Основы разработки`
или я могу на клиенте местами их поменять?

**Comment by Nelfimov** [comment]
@oksssvv Поправил.

**Comment by oxiqod** [comment]
@Nelfimov 
попробовала получить image для карточки, удалось, но цвет другой, я правильно поняла что путь такой: 


```
courses {
    nodes {
      course {
        image{
          sourceUrl
        }
      }
    }
  }
```
на левой карточке получаемое изображение с сервера:
![Снимок экрана от 2023-08-10 11-10-42](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/d6225a5a-2df8-42f4-b947-662af3e8ca86)

**Comment by Nelfimov** [comment]
Все верно. Для картинки надо применить градиентный фильтр.

**Comment by Nelfimov** [comment]
@oksssvv свой косяк поправил - картинка была неправильно выгружена из дизайна.

**Comment by oxiqod** [comment]
@Nelfimov 
мне Андрей сказал что карточки нужно получать с сервера, т.е. как я поняла не верстать в ручную а мапить массив `nodes`

например не совсем ясно как это сделать с имеющимися направляющими (2 карточки идут в Column, затем 2 карточки идут в Row)

можешь пожалуйста поподробнее объяснить как это реализовать? и правильно ли я вообще поняла задачу

**Comment by Nelfimov** [comment]
Все верно - тебе с бэкенда приходят данные, которые нужно размапить с помощью одного компонента Card. 

Расположение в несколько рядов можно добиться двумя путями в CSS:
- flexwrap (предпочтительный) https://css-tricks.com/almanac/properties/f/flex-wrap/
- Grid

**Comment by oxiqod** [comment]
@Nelfimov 

закончила с карточками, есть еще схемы к данным которые нужно получать с сервера?

если есть возможность получить полностью всю схему, то можешь подсказать как ее запросить? 
(чтоб была возможность проверить, не забыла ли я что-то)

**Comment by Nelfimov** [comment]
У нас остался еще вот этот слайдер:

<details>

<img width="495" alt="image" src="https://github.com/atls-academy/oksssvv.github.io/assets/44067768/a9aad9b4-3ba0-4870-833f-4726065455ff">

</details>

У него есть только заголовок. А вообще на странице все данные должны быть взяты из GraphQL, ничего "своего" не должно быть.

Я сообщу как будет готово.

**Comment by Nelfimov** [comment]
Слайд готов, пробуй:

<details>

```graphql
query NewQuery {
  slides {
    nodes {
      slider {
        text
        image {
          link
        }
      }
    }
  }
}
```

</details>

**Comment by Nelfimov** [comment]
Секция Hero доделана, в `content`:

<details>

```graphql
query NewQuery {
  sections {
    nodes {
      content
    }
  }
}
```

</details>

**Comment by Nelfimov** [comment]
Процесс готов

<details>

<img width="698" alt="image" src="https://github.com/atls-academy/oksssvv.github.io/assets/44067768/24aac7f0-e9f8-4211-85de-4bf9998feca4">

```graphql
query NewQuery {
  processes {
    nodes {
      process {
        description
        title
      }
    }
  }
}
```

</details>

**Comment by oxiqod** [comment]
@Nelfimov 
я правильно понимаю, что изображение которое отображается на слайдере это конечный узел с названием `link`?
```query NewQuery {
  slides {
    nodes {
      slider {
        text
        image {
          link
        }
      }
    }
  }
}
```

если да, то он некорректно отображается, и у полученной строки не вижу формат пнг, (например у изображения, которое я получала для карточки) вот что я получаю с сервера

```
"data": {
    "slides": {
      "nodes": [
        {
          "slider": {
            "text": "Формирование системы базовых фрагментов и компонентов",
            "image": {
              "link": "https://wp.api.atls.academy/?attachment_id=141"
            }
          }
        }
      ]
    }
```

**Comment by Nelfimov** [comment]
Обновил настройки - должно сработать. Принцип тот же что и у картинок курсов - `sourceUrl`

**Comment by oxiqod** [comment]
@Nelfimov 
а слайд для мобильной версии или я его не вижу просто?

**Comment by oxiqod** [comment]
@Nelfimov 

еще текст в `description` получаемый в `steps` - не по макету

там фраза обрезана и умещается в 2 строчки, получаемый с сервера текст - в 3 строчки

**Comment by oxiqod** [comment]
@Nelfimov 

макет:
![Снимок экрана от 2023-08-11 20-36-55](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/f5790de0-c1ab-4d42-b6bb-4f942ee0861d)


Приходит с сервера:
![Снимок экрана от 2023-08-11 20-37-44](https://github.com/atls-academy/oksssvv.github.io/assets/126156026/0d65c6da-6e74-4b2d-b24a-a9e2fa427630)

ну т.е. там обрезается фраза для отображения 2х строчек, а с сервера приходит цвелая, я могу ее на клиенте отформатировать на самом то деле, просто подумала что ты не заметил и так не должно быть

**Comment by Nelfimov** [comment]
Добавил слайдеры для мобильного и десктопа, запрос надо полностью переписать:

<details>

```graphql
query NewQuery {
  slides {
    nodes {
      slider {
        text
        imageDesktop {
          sourceUrl
        }
        imageMobile {
          sourceUrl
        }
      }
    }
  }
}
```

</details>
