### ISSUE TITLE
Миграция на tools

### ISSUE THREAD

**Issue by eshevlyakova** [atls-academy/oksssvv.github.io#8]
### Какого рода задача?
Мигрировать авторизацию на tools

###  Что и где будем менять?
Для сборки приложения необходимо использовать `yarn service build`, для запуска в дев режиме - `yarn service dev`

Необходимо оформить файл auth как пакет (воркспейс) с определенной структурой: директория `src` и `index.ts` внутри - [пример](https://github.com/torin-asakura/misik/blob/master/ui/copy/package.json)

Внутри package.json должны находится скрипты для запуска проекта - `build`, `dev` и `start`

`build` билдит проект через `yarn service build` и кладет js в папку `dist`\
`dev` запускает проект в dev режиме\
`start` запускает уже сбилженный проект (`node dist/index.js`)

[Краткий обзор tools](https://github.com/atls/tools/wiki)

### Укажите референс
Приведение проекта к общему стеку

Пример приложения, собирающегося с помощью `yarn service` - https://github.com/torin-asakura/shdvor/blob/5eaf24b8a8cadf25b2ce27f6142ae54fb434dfb7/prices/service-entrypoint/package.json

Пример библиотеки, которая будет публиковаться в npm регистр - https://github.com/atls/nextjs/blob/master/packages/next-sitemap-generator/package.json

**Comment by oxiqod** [comment]
**Вопрос**
папка `dist` , в которую кладется js, создается автоматически или её нужно подготовить?

**Comment by eshevlyakova** [comment]
@oksssvv 

> папка dist , в которую кладется js, создается автоматически или её нужно подготовить?

Автоматически

**Comment by oxiqod** [comment]
@eshevlyakova 

**Скоуп**
Структура проекта

**Описание**
Создание рабочих пространств

**Вопрос**
Для правильной структуры проекта нужно создать под каждый файл.ts(под функции, интерфейс, чеки и тд) отдельную папку с package.json?

**Comment by eshevlyakova** [comment]
@oksssvv В твоем случае пакет авторизации - это набор фичей, то есть содержит несколько функций. Поэтому нет

**Comment by oxiqod** [comment]
@eshevlyakova 

**Скоуп**
Структура проекта

**Описание**
Создание рабочих пространств

**Вопрос**
В папке `auth`  в package.json нужно создать `dependencies` и указать все файлы содержащиеся в `src` со значением `"workspace:0.0.1"` ?

**Comment by eshevlyakova** [comment]
@oksssvv У тебя в dependencies указаны файлы? (Посмотри примеры)

**Comment by oxiqod** [comment]
@eshevlyakova 

>Для правильной структуры проекта нужно создать под каждый файл.ts(под функции, интерфейс, чеки и тд) отдельную папку с package.json?

>В твоем случае пакет авторизации - это набор фичей, то есть содержит несколько функций. Поэтому нет

**Вопрос**
нужно создать папки с package.json под все файлы в src кроме функций?

**Comment by eshevlyakova** [comment]
@oksssvv Я же написала пакет авторизации - это набор функций, то есть твой пакет состоит из нескольких подмодулей/функций

**Comment by oxiqod** [comment]
@eshevlyakova 

**Скоуп**
Рабочая область

**Описание**
Создание рабочей области

**Вопрос**

1. В коренной `package.json` добавить как `workspace` папку `auth`? 
2. Нужно ли указывать в пакедже проекта авторизации `private : true?`

**Comment by eshevlyakova** [comment]
@oksssvv 

> В коренной package.json добавить как workspace папку auth?

Да

> Нужно ли указывать в пакедже проекта авторизации private : true?

Делай по примеру пекеджов на нужном тебе уровне вложенности (указывала в примерах). Вообще если ты указываешь `private : true`, то это означает, что пакет может быть использован только внутри твоего проекта и не может быть установлен другими пользователями

**Comment by oxiqod** [comment]
@eshevlyakova 

**Скоуп**
Рабочая область

**Описание**
Создание рабочей области

**Вопрос**
При указании воркспейса - какое значения имеют `/**/*` после названия папки? 

**Контекст**
[код из примера](https://github.com/torin-asakura/misik/blob/master/package.json#L6-L9)

**Comment by eshevlyakova** [comment]
@oksssvv Это шаблон, который выбирает внутренние папки и файлы этой рабочей области
Тебе достаточно написать название workspace
